name: Publish NuGet Package

on:
  release:
    types: [published]
    
jobs:
  build-and-publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/DictionaryEntry/DictionaryEntry.csproj
      
    - name: Build
      run: dotnet build src/DictionaryEntry/DictionaryEntry.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Pack
      run: dotnet pack src/DictionaryEntry/DictionaryEntry.csproj --configuration Release --no-build --output ./nupkgs
      
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: kjhickman
      
    - name: Push to NuGet.org
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
      